version: "3.5"

services:

  # Superset

  superset:
    image: amancevice/superset:0.28.1
    restart: always
    depends_on:
      - superset-postgres
      - superset-redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./config/superset_config.py:/etc/superset/superset_config.py
    networks:
      - superset_net

  superset-redis:
    image: redis:3.2
    restart: always
    volumes:
      - ${DATADIR}/superset/redis:/data
    networks:
      - superset_net

  superset-postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - ${DATADIR}/superset/postgres:/var/lib/postgresql/data
    networks:
      - superset_net

networks:
  superset_net:
    external:
      name: bigdatanet
